import express from "express";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import crypto from "crypto";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import pg from "pg";
import bcrypt from "bcryptjs";
import { BIS_STANDARDS } from "./src/data/bisDatabase";

dotenv.config();

const app = express();
const PORT = Number(process.env.PORT || 3000);
const isProductionRuntime = process.env.NODE_ENV === "production" || process.env.npm_lifecycle_event === "start";
const sessions = new Map<string, { userId: number; expiresAt: number }>();
const authAttempts = new Map<string, { count: number; resetAt: number }>();
const { Pool } = pg;
const dbPool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_SSL === "false" ? false : { rejectUnauthorized: false },
  max: 10,
});

app.use(express.json({ limit: "256kb" }));
app.use((req, res, next) => {
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("X-Frame-Options", "DENY");
  res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
  res.setHeader(
    "Content-Security-Policy",
    isProductionRuntime
      ? "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self'; connect-src 'self' https://*.supabase.co https://openrouter.ai"
      : "default-src 'self' http://localhost:* http://127.0.0.1:*; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' ws: wss: https://*.supabase.co https://openrouter.ai",
  );
  if (["POST", "PUT", "PATCH", "DELETE"].includes(req.method)) {
    const origin = req.headers.origin;
    const allowedOrigins = new Set([
      `${req.protocol}://${req.get("host")}`,
      process.env.VITE_APP_URL,
    ].filter(Boolean));
    if (origin && !allowedOrigins.has(origin)) {
      return res.status(403).json({ message: "Cross-site request blocked." });
    }
  }
  next();
});

function enforceAuthRateLimit(req: express.Request, res: express.Response): boolean {
  const key = req.ip || "unknown";
  const now = Date.now();
  const attempt = authAttempts.get(key);
  if (!attempt || attempt.resetAt <= now) {
    authAttempts.set(key, { count: 1, resetAt: now + 15 * 60 * 1000 });
    return true;
  }
  attempt.count += 1;
  if (attempt.count > 10) {
    res.status(429).json({ message: "Too many authentication attempts. Try again later." });
    return false;
  }
  return true;
}

function setSessionCookie(res: express.Response, userId: number) {
  const token = crypto.randomBytes(32).toString("hex");
  sessions.set(token, { userId, expiresAt: Date.now() + 1000 * 60 * 60 * 24 * 7 });
  res.setHeader("Set-Cookie", `bis_session=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800${isProductionRuntime ? "; Secure" : ""}`);
}

function getSessionUserId(req: express.Request): number | null {
  const token = req.headers.cookie?.match(/(?:^|;\s*)bis_session=([^;]+)/)?.[1];
  if (!token) return null;
  const session = sessions.get(token);
  if (!session || session.expiresAt < Date.now()) {
    sessions.delete(token);
    return null;
  }
  return session.userId;
}

function requireSession(req: express.Request, res: express.Response): number | null {
  const userId = getSessionUserId(req);
  if (!userId) {
    res.status(401).json({ message: "Authentication is required." });
    return null;
  }
  return userId;
}

async function initializeDatabase() {
  try {
    await dbPool.query(`
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE,
        password_hash VARCHAR(255) NOT NULL,
        phone VARCHAR(50) DEFAULT NULL,
        organisation VARCHAR(255) DEFAULT NULL,
        role VARCHAR(255) DEFAULT NULL,
        region VARCHAR(255) DEFAULT NULL,
        access_type VARCHAR(255) DEFAULT 'Enterprise portal',
        profile_image TEXT DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    `);

    await dbPool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(50) DEFAULT NULL;`);
    await dbPool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image TEXT DEFAULT NULL;`);

    await dbPool.query(`
      CREATE TABLE IF NOT EXISTS standards (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        is_code VARCHAR(255) NOT NULL UNIQUE,
        title VARCHAR(255) NOT NULL,
        category VARCHAR(255) DEFAULT NULL,
        department VARCHAR(255) DEFAULT NULL,
        summary TEXT,
        scope TEXT,
        is_mandatory_qco BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    `);

    await dbPool.query(`
      CREATE TABLE IF NOT EXISTS standard_finder_index (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        is_code VARCHAR(255) NOT NULL UNIQUE,
        title VARCHAR(500) NOT NULL,
        category VARCHAR(255),
        department VARCHAR(255),
        year VARCHAR(20),
        summary TEXT,
        scope TEXT,
        is_mandatory_qco BOOLEAN NOT NULL DEFAULT FALSE,
        source TEXT,
        search_text TEXT NOT NULL,
        record_payload JSONB NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    `);

    await dbPool.query(`CREATE INDEX IF NOT EXISTS idx_finder_code ON standard_finder_index (is_code);`);
    await dbPool.query(`CREATE INDEX IF NOT EXISTS idx_finder_search_text ON standard_finder_index USING gin (to_tsvector('simple', search_text));`);

    await dbPool.query(`
      CREATE TABLE IF NOT EXISTS chat_conversations (
        id CHAR(36) PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        title VARCHAR(160) NOT NULL DEFAULT 'New conversation',
        mode VARCHAR(20) NOT NULL DEFAULT 'consumer' CHECK (mode IN ('consumer', 'industry')),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    `);

    await dbPool.query(`
      CREATE TABLE IF NOT EXISTS chat_messages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversation_id CHAR(36) NOT NULL,
        user_id INTEGER NULL,
        sender VARCHAR(20) NOT NULL CHECK (sender IN ('user', 'assistant', 'system')),
        message_text TEXT NOT NULL,
        mode VARCHAR(20) NOT NULL DEFAULT 'consumer' CHECK (mode IN ('consumer', 'industry')),
        confidence VARCHAR(20) NULL,
        cited_clauses JSONB NULL,
        source_card JSONB NULL,
        suggested_actions JSONB NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
      );
    `);

    await dbPool.query(`CREATE INDEX IF NOT EXISTS idx_chat_conversation ON chat_messages (conversation_id);`);
    await dbPool.query(`CREATE INDEX IF NOT EXISTS idx_chat_user ON chat_messages (user_id);`);
    await dbPool.query(`CREATE INDEX IF NOT EXISTS idx_chat_created ON chat_messages (created_at);`);
    await dbPool.query(`CREATE INDEX IF NOT EXISTS idx_chat_conversations_user_updated ON chat_conversations (user_id, updated_at DESC);`);

    await dbPool.query(`
      INSERT INTO chat_conversations (id, user_id, title, mode, created_at, updated_at)
      SELECT first_message.conversation_id, first_message.user_id,
             LEFT(first_message.message_text, 160), first_message.mode,
             first_message.created_at, latest_message.created_at
      FROM (
        SELECT DISTINCT ON (conversation_id, user_id)
          TRIM(conversation_id) AS conversation_id, user_id, message_text, mode, created_at
        FROM chat_messages
        WHERE user_id IS NOT NULL AND sender = 'user'
        ORDER BY conversation_id, user_id, created_at ASC, id ASC
      ) AS first_message
      JOIN (
        SELECT TRIM(conversation_id) AS conversation_id, user_id, MAX(created_at) AS created_at
        FROM chat_messages
        WHERE user_id IS NOT NULL
        GROUP BY conversation_id, user_id
      ) AS latest_message
        ON latest_message.conversation_id = first_message.conversation_id
       AND latest_message.user_id = first_message.user_id
      ON CONFLICT (id) DO NOTHING;
    `);

    const standardsToInsert = BIS_STANDARDS.map((standard) => [
      standard.isCode,
      standard.title,
      standard.category,
      standard.department,
      standard.summary,
      standard.scope || '',
      standard.isMandatoryQCO ? 1 : 0,
    ]);

    if (standardsToInsert.length > 0) {
      for (const standard of standardsToInsert) {
        await dbPool.query(
          `INSERT INTO standards (is_code, title, category, department, summary, scope, is_mandatory_qco)
           VALUES ($1, $2, $3, $4, $5, $6, $7)
           ON CONFLICT (is_code) DO UPDATE SET
             title = EXCLUDED.title,
             category = EXCLUDED.category,
             department = EXCLUDED.department,
             summary = EXCLUDED.summary,
             scope = EXCLUDED.scope,
             is_mandatory_qco = EXCLUDED.is_mandatory_qco`,
          standard
        );
      }
    }

    const finderRecords = indexedStandardRecords();
    const { rows: finderCountRows } = await dbPool.query('SELECT COUNT(*)::int AS count FROM standard_finder_index');
    if (finderCountRows[0].count !== finderRecords.length) {
      const columns = '(is_code, title, category, department, year, summary, scope, is_mandatory_qco, source, search_text, record_payload, updated_at)';
      for (let start = 0; start < finderRecords.length; start += 100) {
        const chunk = finderRecords.slice(start, start + 100);
        const values: unknown[] = [];
        const placeholders = chunk.map((record, index) => {
          const searchText = [record.isCode, record.title, record.category, record.department, record.year, record.summary, record.scope, record.source]
            .filter(Boolean).join(' ');
          values.push(
            record.isCode,
            record.title || `${record.isCode} - BIS standard record`,
            record.category || 'Standards / Dataset',
            record.department || 'BIS',
            record.year || 'Not specified',
            record.summary || '',
            record.scope || '',
            Boolean(record.isMandatoryQCO),
            record.source || 'BIS Database',
            searchText,
            JSON.stringify(record),
          );
          const offset = index * 11;
          return `($${offset + 1}, $${offset + 2}, $${offset + 3}, $${offset + 4}, $${offset + 5}, $${offset + 6}, $${offset + 7}, $${offset + 8}, $${offset + 9}, $${offset + 10}, $${offset + 11}::jsonb, CURRENT_TIMESTAMP)`;
        }).join(',');

        await dbPool.query(
          `INSERT INTO standard_finder_index ${columns}
           VALUES ${placeholders}
           ON CONFLICT (is_code) DO UPDATE SET
             title = EXCLUDED.title,
             category = EXCLUDED.category,
             department = EXCLUDED.department,
             year = EXCLUDED.year,
             summary = EXCLUDED.summary,
             scope = EXCLUDED.scope,
             is_mandatory_qco = EXCLUDED.is_mandatory_qco,
             source = EXCLUDED.source,
             search_text = EXCLUDED.search_text,
             record_payload = EXCLUDED.record_payload,
             updated_at = CURRENT_TIMESTAMP`,
          values,
        );
      }
    }

    console.log("Supabase PostgreSQL database initialized");
  } catch (error) {
    console.error("Supabase PostgreSQL initialization failed:", error);
    throw error;
  }
}

// Lazy-initialize Gemini AI Client
function getGeminiClient(): GoogleGenAI | null {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return null;
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });
}

async function callOpenRouter(prompt: string, mode: string = 'consumer') {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    return null;
  }

  const model = process.env.OPENROUTER_MODEL || process.env.BIS_LLM_MODEL || 'openai/gpt-4o-mini';
  const baseUrl = (process.env.OPENROUTER_BASE_URL || process.env.OPENROUTER_API_BASE || 'https://openrouter.ai/api/v1').replace(/\/$/, '');

  const systemInstruction = `You are "BIS Sahayak", the Bureau of Indian Standards AI assistant. Answer in ${mode === 'consumer' ? 'consumer-friendly plain language' : 'technical industry language'}. Use BIS Indian Standards, QCOs, Hallmarking, and certification guidance. Cite relevant IS codes and clauses when possible. Do not invent unsupported facts.

Response rules: answer directly in 3 to 5 short bullet points. Keep each bullet to one clear sentence. Use simple words, remove repetition and filler, and do not write long paragraphs. Include only the details needed to answer the user's question.`;

  const response = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': 'http://localhost:3000',
      'X-Title': 'BIS Sahayak',
    },
    body: JSON.stringify({
      model,
      temperature: 0.2,
      messages: [
        { role: 'system', content: systemInstruction },
        { role: 'user', content: prompt }
      ],
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`OpenRouter request failed (${response.status}): ${text}`);
  }

  const data = await response.json();
  const rawText = data?.choices?.[0]?.message?.content || 'No response received from model.';
  const lowerPrompt = (prompt || '').toLowerCase();

  let matchedIS = 'IS 14543:2016';
  let matchedTitle = 'Packaged Drinking Water (Other than Natural Mineral Water) — Specification';
  let matchedCategory = 'Mandatory QCO';
  const citedClauses = [
    { clause: 'Clause 4.1', description: 'Mandatory multi-barrier treatment and disinfection requirements.' },
    { clause: 'Table 2 & 3', description: 'Chemical and toxic substance limits.' }
  ];

  if (lowerPrompt.includes('10500') || (lowerPrompt.includes('drinking water') && !lowerPrompt.includes('packaged'))) {
    matchedIS = 'IS 10500:2012';
    matchedTitle = 'Drinking Water — Specification (Second Revision)';
    matchedCategory = 'Civil & Public Health';
  } else if (lowerPrompt.includes('456') || lowerPrompt.includes('concrete') || lowerPrompt.includes('cement')) {
    matchedIS = 'IS 456:2000';
    matchedTitle = 'Plain and Reinforced Concrete — Code of Practice';
    matchedCategory = 'Civil Engineering Division';
  } else if (lowerPrompt.includes('toy') || lowerPrompt.includes('9873') || lowerPrompt.includes('child')) {
    matchedIS = 'IS 9873 (Part 1):2019';
    matchedTitle = 'Safety of Toys — Mechanical and Physical Properties';
    matchedCategory = 'Consumer Goods & Child Safety';
  } else if (lowerPrompt.includes('plug') || lowerPrompt.includes('socket') || lowerPrompt.includes('1293')) {
    matchedIS = 'IS 1293:2019';
    matchedTitle = 'Plugs and Socket-Outlets for Domestic Purposes — Specification';
    matchedCategory = 'Electrotechnical Division';
  } else if (lowerPrompt.includes('steel') || lowerPrompt.includes('tmt') || lowerPrompt.includes('1786') || lowerPrompt.includes('rebar')) {
    matchedIS = 'IS 1786:2008';
    matchedTitle = 'High Strength Deformed Steel Bars and Wires for Concrete Reinforcement';
    matchedCategory = 'Metallurgical Division';
  } else if (lowerPrompt.includes('13252') || lowerPrompt.includes('laptop') || lowerPrompt.includes('electronics') || lowerPrompt.includes('crs')) {
    matchedIS = 'IS 13252 (Part 1):2010';
    matchedTitle = 'Information Technology Equipment — Safety — General Requirements';
    matchedCategory = 'Electronics & IT (CRS)';
  } else if (lowerPrompt.includes('gold') || lowerPrompt.includes('hallmark') || lowerPrompt.includes('huid') || lowerPrompt.includes('1417')) {
    matchedIS = 'IS 1417:2016';
    matchedTitle = 'Gold and Gold Alloys, Silver and Silver Alloys — Jewellery/Artefacts';
    matchedCategory = 'Hallmarking Assaying';
  }

  return {
    text: formatAssistantAnswer(rawText),
    confidence: 'high',
    citedClauses,
    sourceCard: {
      isCode: matchedIS,
      title: matchedTitle,
      category: matchedCategory,
    },
    suggestedActions: [
      { label: 'Download Excerpt', actionType: 'download', payload: matchedIS },
      { label: 'Compare with ISO', actionType: 'compare', payload: matchedIS },
    ],
  };
}

function formatAssistantAnswer(text: string): string {
  const normalized = String(text || '').replace(/\r/g, '').trim();
  if (!normalized) return 'No response received from the BIS assistant.';

  const existingPoints = normalized
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => /^([-*•]|\d+[.)])\s+/.test(line));

  if (existingPoints.length >= 2) {
    return existingPoints.slice(0, 5).join('\n');
  }

  const sentences = normalized
    .replace(/\s+/g, ' ')
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => sentence.trim())
    .filter(Boolean)
    .slice(0, 5);

  return sentences.map((sentence) => `- ${sentence}`).join('\n');
}

// Health endpoint
app.get("/api/health", async (req, res) => {
  let dbStatus = "disconnected";

  try {
    const { rows } = await dbPool.query("SELECT 1 AS ok");
    dbStatus = rows.length > 0 ? "connected" : "disconnected";
  } catch (error) {
    dbStatus = "disconnected";
  }

  res.json({
    status: "ok",
    timestamp: new Date().toISOString(),
    hasApiKey: Boolean(process.env.OPENROUTER_API_KEY || process.env.GEMINI_API_KEY),
    providers: {
      openRouter: Boolean(process.env.OPENROUTER_API_KEY),
      gemini: Boolean(process.env.GEMINI_API_KEY),
    },
    appName: "BIS Sahayak",
    dbStatus,
  });
});

app.post("/api/auth/signup", async (req, res) => {
  try {
    if (!enforceAuthRateLimit(req, res)) return;
    const { name, email, password, organisation, role, region } = req.body ?? {};

    if (!name || !email || !password) {
      return res.status(400).json({ message: "Name, email and password are required." });
    }

    const safeEmail = String(email).trim().toLowerCase();
    const safeName = String(name).trim();
    const safeOrganisation = String(organisation ?? "").trim();
    const safeRole = String(role ?? "").trim();
    const safeRegion = String(region ?? "").trim();

    const { rows: existingRows } = await dbPool.query(
      "SELECT id FROM users WHERE email = $1 LIMIT 1",
      [safeEmail]
    );

    if (existingRows.length > 0) {
      return res.status(409).json({ message: "This account already exists. Please sign in instead." });
    }

    const passwordHash = await bcrypt.hash(String(password), 10);

     const { rows: insertedUsers } = await dbPool.query(
      `INSERT INTO users (name, email, password_hash, phone, organisation, role, region, access_type)
       VALUES ($1, $2, $3, $4, $5, $6, $7, 'Enterprise portal')
       RETURNING id`,
      [safeName, safeEmail, passwordHash, '', safeOrganisation, safeRole, safeRegion]
    );
    setSessionCookie(res, insertedUsers[0].id);

    return res.status(201).json({
      message: "User registered successfully.",
      user: {
        id: insertedUsers[0].id,
        name: safeName,
        email: safeEmail,
        organisation: safeOrganisation,
        role: safeRole,
        region: safeRegion,
      },
    });
  } catch (error: any) {
    console.error("Signup error:", error);
    if (error?.code === "23505") {
      return res.status(409).json({ message: "This email is already registered." });
    }

    return res.status(500).json({ message: "Internal server error during signup." });
  }
});

app.post("/api/auth/login", async (req, res) => {
  try {
    if (!enforceAuthRateLimit(req, res)) return;
    const { email, password } = req.body ?? {};

    if (!email || !password) {
      return res.status(400).json({ message: "Email and password are required." });
    }

    const safeEmail = String(email).trim().toLowerCase();
    const { rows } = await dbPool.query(
      "SELECT * FROM users WHERE email = $1 LIMIT 1",
      [safeEmail]
    );

    if (!rows.length) {
      return res.status(401).json({ message: "Invalid email or password." });
    }

    const user = rows[0];
    const passwordMatches = await bcrypt.compare(String(password), user.password_hash);

    if (!passwordMatches) {
      return res.status(401).json({ message: "Invalid email or password." });
    }

    setSessionCookie(res, user.id);

    return res.json({
      message: "Login successful.",
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        phone: user.phone || '',
        organisation: user.organisation,
        role: user.role,
        region: user.region,
        accessType: user.access_type,
        profileImage: user.profile_image || '',
      },
    });
  } catch (error) {
    console.error("Login error:", error);
    return res.status(500).json({ message: "Internal server error during login." });
  }
});

app.post("/api/auth/oauth", async (req, res) => {
  try {
    const { email, name, avatarUrl } = req.body ?? {};
    const safeEmail = String(email ?? '').trim().toLowerCase();
    if (!safeEmail) {
      return res.status(400).json({ message: "OAuth account email is required." });
    }

    const { rows } = await dbPool.query(
      `INSERT INTO users (name, email, password_hash, phone, profile_image)
       VALUES ($1, $2, $3, $4, $5)
       ON CONFLICT (email) DO UPDATE SET
         name = COALESCE(NULLIF(EXCLUDED.name, ''), users.name),
         profile_image = COALESCE(NULLIF(EXCLUDED.profile_image, ''), users.profile_image),
         updated_at = CURRENT_TIMESTAMP
       RETURNING id, name, email, organisation, role, region, access_type, profile_image`,
      [String(name ?? '').trim() || safeEmail.split('@')[0], safeEmail, 'supabase-oauth-account', '', String(avatarUrl ?? '').trim() || null]
    );

    const user = rows[0];
    setSessionCookie(res, user.id);
    return res.json({
      message: "OAuth login successful.",
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        phone: user.phone || '',
        organisation: user.organisation,
        role: user.role,
        region: user.region,
        accessType: user.access_type,
        profileImage: user.profile_image || '',
      },
    });
  } catch (error) {
    console.error("OAuth login error:", error);
    return res.status(500).json({ message: "Unable to create the OAuth profile." });
  }
});

app.post("/api/auth/logout", (req, res) => {
  const token = req.headers.cookie?.match(/(?:^|;\s*)bis_session=([^;]+)/)?.[1];
  if (token) sessions.delete(token);
  res.setHeader("Set-Cookie", "bis_session=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0");
  return res.json({ loggedOut: true });
});

app.put("/api/users/:id/profile", async (req, res) => {
  try {
    const userId = Number(req.params.id);
    const sessionUserId = requireSession(req, res);
    if (!sessionUserId) return;
    if (sessionUserId !== userId) {
      return res.status(403).json({ message: "You can only update your own profile." });
    }
    const { name, email, phone, organisation, role, region, accessType, profileImage } = req.body ?? {};
    if (!Number.isInteger(userId) || !String(name ?? '').trim() || !String(email ?? '').trim()) {
      return res.status(400).json({ message: "A valid user id, name and email are required." });
    }

    const { rows } = await dbPool.query(
      `UPDATE users SET
         name = $1,
         email = $2,
         phone = $3,
         organisation = $4,
         role = $5,
         region = $6,
         access_type = $7,
         profile_image = $8,
         updated_at = CURRENT_TIMESTAMP
       WHERE id = $9
       RETURNING id, name, email, organisation, role, region, access_type, profile_image`,
      [String(name).trim(), String(email).trim().toLowerCase(), String(phone ?? '').trim() || null, String(organisation ?? '').trim() || null, String(role ?? '').trim() || null, String(region ?? '').trim() || null, String(accessType ?? 'Enterprise portal'), String(profileImage ?? '').trim() || null, userId]
    );

    if (!rows.length) {
      return res.status(404).json({ message: "User profile was not found." });
    }

    const user = rows[0];
    return res.json({
      message: "Profile saved successfully.",
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        phone: String(phone ?? ''),
        organisation: user.organisation || '',
        role: user.role || '',
        region: user.region || '',
        accessType: user.access_type || 'Enterprise portal',
        profileImage: user.profile_image || '',
      },
    });
  } catch (error: any) {
    console.error("Profile save error:", error);
    if (error?.code === "23505") {
      return res.status(409).json({ message: "That email is already in use." });
    }
    return res.status(500).json({ message: "Unable to save profile." });
  }
});

app.get("/api/chat/conversations", async (req, res) => {
  try {
    const userId = Number(req.query.userId);
    const sessionUserId = requireSession(req, res);
    if (!sessionUserId) return;
    if (sessionUserId !== userId) {
      return res.status(403).json({ message: "You can only view your own conversations." });
    }
    if (!Number.isInteger(userId)) {
      return res.status(400).json({ message: "A valid userId is required." });
    }

    const { rows } = await dbPool.query(
            `SELECT c.id, c.title, c.mode, c.created_at, c.updated_at,
              u.name AS user_name, u.email AS user_email,
              COUNT(m.id)::int AS message_count
       FROM chat_conversations c
             INNER JOIN users u ON u.id = c.user_id
       LEFT JOIN chat_messages m ON m.conversation_id = c.id AND m.user_id = c.user_id
       WHERE c.user_id = $1
             GROUP BY c.id, u.name, u.email
       ORDER BY c.updated_at DESC
       LIMIT 50`,
      [userId],
    );

    return res.json({ conversations: rows });
  } catch (error) {
    console.error("Chat conversations fetch error:", error);
    return res.status(500).json({ message: "Unable to fetch chat conversations." });
  }
});

// Load IS codes from local dataset and official BIS website index
let isCodesIndex: Record<string, any> = {};
let officialIsCodesIndex: Record<string, any> = {};
try {
  const serverDirectory = typeof __dirname === 'string'
    ? __dirname
    : path.dirname(fileURLToPath(import.meta.url));
  const indexCandidates = [
    path.resolve(serverDirectory, '..', 'bis_rag', 'data', 'is_codes_index.json'),
    path.resolve(process.cwd(), 'bis_rag', 'data', 'is_codes_index.json'),
    path.resolve(process.cwd(), '..', 'bis_rag', 'data', 'is_codes_index.json'),
  ];
  const officialIndexCandidates = [
    path.resolve(serverDirectory, '..', 'bis_rag', 'data', 'official_bis_index.json'),
    path.resolve(process.cwd(), 'bis_rag', 'data', 'official_bis_index.json'),
    path.resolve(process.cwd(), '..', 'bis_rag', 'data', 'official_bis_index.json'),
  ];

  const datasetIndexPath = indexCandidates.find((candidate) => fs.existsSync(candidate));
  if (datasetIndexPath) {
    isCodesIndex = JSON.parse(fs.readFileSync(datasetIndexPath, 'utf-8'));
    console.log(`Loaded ${Object.keys(isCodesIndex).length} IS codes from dataset index`);
  } else {
    console.warn(`IS codes index not found. Checked: ${indexCandidates.join(', ')}`);
  }

  const officialIndexPath = officialIndexCandidates.find((candidate) => fs.existsSync(candidate));
  if (officialIndexPath) {
    officialIsCodesIndex = JSON.parse(fs.readFileSync(officialIndexPath, 'utf-8'));
    console.log(`Loaded ${Object.keys(officialIsCodesIndex).length} official BIS records from Selenium index`);
  } else {
    console.warn(`Official BIS Selenium index not found. Checked: ${officialIndexCandidates.join(', ')}`);
  }
} catch (err) {
  console.warn('Unable to load IS codes index, will use database only:', err);
}

const mergedIsCodesIndex: Record<string, any> = { ...isCodesIndex, ...officialIsCodesIndex };

app.get("/api/standards", async (req, res) => {
  try {
    const { rows } = await dbPool.query(
      `SELECT id, is_code, title, category, department, summary, scope, is_mandatory_qco
       FROM standards
       ORDER BY is_code ASC`
    );

    return res.json({
      count: rows.length,
      standards: rows,
    });
  } catch (error) {
    console.error("Standards fetch error:", error);
    return res.status(500).json({ message: "Unable to fetch standards." });
  }
});

app.post("/api/chat/messages", async (req, res) => {
  try {
    const { conversationId, userId, sender, messageText, mode = "consumer", confidence, citedClauses, sourceCard, suggestedActions } = req.body ?? {};

    if (!conversationId || !userId || !messageText || !['user', 'assistant', 'system'].includes(sender)) {
      return res.status(400).json({ message: "conversationId, userId, sender and messageText are required." });
    }

    const sessionUserId = requireSession(req, res);
    if (!sessionUserId) return;
    if (sessionUserId !== Number(userId)) {
      return res.status(403).json({ message: "You can only save messages to your own conversations." });
    }

    const { rows: users } = await dbPool.query(
      "SELECT id FROM users WHERE id = $1 LIMIT 1",
      [Number(userId)]
    );

    if (!users.length) {
      return res.status(401).json({ message: "Authenticated user was not found." });
    }

    const normalizedConversationId = String(conversationId).trim();
    const normalizedMode = mode === "industry" ? "industry" : "consumer";
    const { rows: existingConversations } = await dbPool.query(
      "SELECT id FROM chat_conversations WHERE id = $1 AND user_id = $2 LIMIT 1",
      [normalizedConversationId, users[0].id],
    );

    if (!existingConversations.length) {
      const { rows: conflictingConversations } = await dbPool.query(
        "SELECT id FROM chat_conversations WHERE id = $1 LIMIT 1",
        [normalizedConversationId],
      );
      if (conflictingConversations.length) {
        return res.status(403).json({ message: "This conversation belongs to another user." });
      }

      await dbPool.query(
        `INSERT INTO chat_conversations (id, user_id, title, mode)
         VALUES ($1, $2, $3, $4)`,
        [normalizedConversationId, users[0].id, String(messageText).trim().slice(0, 160) || "New conversation", normalizedMode],
      );
    } else {
      await dbPool.query(
        `UPDATE chat_conversations
         SET mode = $1,
             title = CASE WHEN title = 'New conversation' AND $2 = 'user' THEN LEFT($3, 160) ELSE title END,
             updated_at = CURRENT_TIMESTAMP
         WHERE id = $4 AND user_id = $5`,
        [normalizedMode, sender, String(messageText), normalizedConversationId, users[0].id],
      );
    }

    await dbPool.query(
      `INSERT INTO chat_messages
       (conversation_id, user_id, sender, message_text, mode, confidence, cited_clauses, source_card, suggested_actions)
       VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8::jsonb, $9::jsonb)`,
      [
        normalizedConversationId,
        users[0].id,
        sender,
        String(messageText),
        normalizedMode,
        confidence ? String(confidence) : null,
        citedClauses ? JSON.stringify(citedClauses) : null,
        sourceCard ? JSON.stringify(sourceCard) : null,
        suggestedActions ? JSON.stringify(suggestedActions) : null,
      ]
    );

    await dbPool.query(
      `UPDATE chat_conversations
       SET updated_at = CURRENT_TIMESTAMP
       WHERE id = $1 AND user_id = $2`,
      [normalizedConversationId, users[0].id],
    );

    return res.status(201).json({ saved: true });
  } catch (error) {
    console.error("Chat message save error:", error);
    return res.status(500).json({ message: "Unable to save chat message." });
  }
});

app.get("/api/chat/messages/:conversationId", async (req, res) => {
  try {
    const { conversationId } = req.params;
    const userId = Number(req.query.userId);
    const sessionUserId = requireSession(req, res);
    if (!sessionUserId) return;
    if (sessionUserId !== userId) {
      return res.status(403).json({ message: "You can only view your own messages." });
    }

    if (!conversationId || !Number.isInteger(userId)) {
      return res.status(400).json({ message: "conversationId and userId are required." });
    }

    const { rows } = await dbPool.query(
      `SELECT id, sender, message_text, mode, confidence, cited_clauses, source_card, suggested_actions, created_at
       FROM chat_messages
       WHERE conversation_id = $1 AND user_id = $2
       ORDER BY created_at ASC, id ASC`,
      [conversationId, userId]
    );

    return res.json({ messages: rows });
  } catch (error) {
    console.error("Chat history fetch error:", error);
    return res.status(500).json({ message: "Unable to fetch chat history." });
  }
});

function normalizeStandardCode(code: string) {
  return code.toUpperCase().replace(/[^A-Z0-9]/g, '');
}

function toStandardRecord(code: string, metadata: Record<string, any> = {}) {
  const catalogRecord = BIS_STANDARDS.find(
    (standard) => normalizeStandardCode(standard.isCode) === normalizeStandardCode(code),
  );

  if (catalogRecord) {
    return {
      code: catalogRecord.isCode,
      ...catalogRecord,
      source: metadata.source || 'BIS standards catalog',
      year: metadata.year || catalogRecord.year,
    };
  }

  return {
    code,
    id: `iso-${normalizeStandardCode(code).toLowerCase()}`,
    isCode: code,
    year: metadata.year || 'Not specified',
    title: `${code} - BIS standard record`,
    category: metadata.category || 'Standards / Dataset',
    department: metadata.department || 'BIS',
    isMandatoryQCO: Boolean(metadata.isMandatoryQCO),
    summary: `IS number found in the BIS dataset. Source: ${metadata.source || 'BIS Database'}`,
    scope: 'The detailed scope is not available in the indexed record.',
    keyClauses: [],
    isoEquivalence: '',
    isoComparisonNotes: '',
    sampleTestParameters: [],
    pdfExcerptSnippet: metadata.source ? `Source file: ${metadata.source}` : undefined,
    viewsCount: 0,
    lastUpdated: 'Dataset',
    source: metadata.source || 'BIS Database',
  };
}

function indexedStandardRecords() {
  const mergedIndex = { ...isCodesIndex, ...officialIsCodesIndex };
  const indexedCodes = Object.keys(mergedIndex)
    .filter((code) => code.toUpperCase().startsWith('IS'))
    .map((code) => toStandardRecord(code, mergedIndex[code]));

  const catalogCodes = BIS_STANDARDS.map((standard) => toStandardRecord(standard.isCode));
  const records = [...indexedCodes, ...catalogCodes];
  const unique = new Map<string, any>();

  records.forEach((record) => unique.set(normalizeStandardCode(record.isCode), record));
  return Array.from(unique.values());
}

// IS codes search endpoint
app.get("/api/is-codes/search", async (req, res) => {
  const query = String(req.query.q || '').trim();

  if (query.length < 2) {
    return res.json({ codes: [], total: 0 });
  }

  try {
    const normalizedQuery = normalizeStandardCode(query);
    const { rows } = await dbPool.query(
      `SELECT is_code, source, record_payload
       FROM standard_finder_index
       WHERE regexp_replace(upper(is_code), '[^A-Z0-9]', '', 'g') LIKE $1
          OR search_text ILIKE $2
       ORDER BY CASE WHEN regexp_replace(upper(is_code), '[^A-Z0-9]', '', 'g') = $3 THEN 0 ELSE 1 END,
                updated_at DESC
       LIMIT 50`,
      [`%${normalizedQuery}%`, `%${query}%`, normalizedQuery],
    );
    const results = rows.map((row) => ({ ...row.record_payload, code: row.is_code, isCode: row.is_code, source: row.source }));
    return res.json({ codes: results, total: results.length, query });
  } catch (error) {
    console.error('Standard Finder database search error:', error);
    return res.status(500).json({ message: 'Unable to search the Standard Finder index.' });
  }
});

// IS codes list endpoint
app.get("/api/is-codes", async (req, res) => {
  try {
    const { rows } = await dbPool.query(
      `SELECT is_code, source, record_payload
       FROM standard_finder_index
       ORDER BY is_code ASC
       LIMIT 500`,
    );
    const totalResult = await dbPool.query('SELECT COUNT(*)::int AS total FROM standard_finder_index');
    const codes = rows.map((row) => ({ ...row.record_payload, code: row.is_code, isCode: row.is_code, source: row.source }));
    return res.json({ codes, total: totalResult.rows[0].total });
  } catch (error) {
    console.error('Standard Finder database list error:', error);
    return res.status(500).json({ message: 'Unable to load the Standard Finder index.' });
  }
});

// Standard detail endpoint used by the finder and future deep links.
app.get("/api/is-codes/:code", async (req, res) => {
  const code = decodeURIComponent(req.params.code);
  try {
    const { rows } = await dbPool.query(
      `SELECT is_code, source, record_payload
       FROM standard_finder_index
       WHERE regexp_replace(upper(is_code), '[^A-Z0-9]', '', 'g') = $1
       LIMIT 1`,
      [normalizeStandardCode(code)],
    );

    if (!rows.length) {
      return res.status(404).json({ message: 'IS standard was not found.' });
    }

    return res.json({ ...rows[0].record_payload, code: rows[0].is_code, isCode: rows[0].is_code, source: rows[0].source });
  } catch (error) {
    console.error('Standard Finder database detail error:', error);
    return res.status(500).json({ message: 'Unable to load the Standard Finder record.' });
  }
});

// Licence Verification API endpoint
app.post("/api/verify-licence", (req, res) => {
  const { licenceNumber } = req.body;
  if (!licenceNumber) {
    return res.status(400).json({ error: "Licence number is required" });
  }

  const cleanNum = String(licenceNumber).trim().toUpperCase();

  // Pattern matching for CM/L or R-numbers
  if (cleanNum.startsWith("CM/L-") || cleanNum.startsWith("CML") || /^\d{7,8}$/.test(cleanNum)) {
    const isWater = cleanNum.includes("1454") || cleanNum.endsWith("5");
    const isSteel = cleanNum.includes("1786") || cleanNum.endsWith("8");

    if (isWater) {
      return res.json({
        valid: true,
        licenceNumber: cleanNum.startsWith("CM/L-") ? cleanNum : `CM/L-${cleanNum}`,
        manufacturerName: "Himalayan Natural Springs Bottling Pvt Ltd",
        factoryAddress: "Plot 42, Sector 8, Industrial Estate, Haridwar, Uttarakhand - 249403",
        isCode: "IS 14543:2016",
        productName: "Packaged Drinking Water (Other than Natural Mineral Water)",
        brandName: "AquaPure Gold",
        validFrom: "2023-04-01",
        validTo: "2028-03-31",
        status: "Operative",
        scheme: "Scheme-I (ISI Mark)"
      });
    } else if (isSteel) {
      return res.json({
        valid: true,
        licenceNumber: cleanNum.startsWith("CM/L-") ? cleanNum : `CM/L-${cleanNum}`,
        manufacturerName: "Bharat TMT Steels & Alloys Ltd",
        factoryAddress: "Industrial Growth Centre, Phase II, Raipur, Chhattisgarh - 492001",
        isCode: "IS 1786:2008",
        productName: "High Strength Deformed Steel Bars (Fe 500D) for RCC",
        brandName: "BHARAT-500D TMT",
        validFrom: "2022-01-15",
        validTo: "2027-01-14",
        status: "Operative",
        scheme: "Scheme-I (ISI Mark)"
      });
    } else {
      return res.json({
        valid: true,
        licenceNumber: cleanNum.startsWith("CM/L-") ? cleanNum : `CM/L-${cleanNum}`,
        manufacturerName: "Suraksha Poly-Plast Industries India",
        factoryAddress: "Survey No. 112, GIDC Industrial Estate, Vadodara, Gujarat - 390010",
        isCode: "IS 1293:2019",
        productName: "Plugs and Socket-Outlets up to 16A 250V AC",
        brandName: "SAFEPLUG PRO",
        validFrom: "2024-02-10",
        validTo: "2029-02-09",
        status: "Operative",
        scheme: "Scheme-I (ISI Mark)"
      });
    }
  } else if (cleanNum.startsWith("R-") || cleanNum.startsWith("CRS")) {
    return res.json({
      valid: true,
      licenceNumber: cleanNum.startsWith("R-") ? cleanNum : `R-${cleanNum}`,
      manufacturerName: "Foxconn Electronics Technology (India) Pvt Ltd",
      factoryAddress: "SIPCOT Hi-Tech SEZ, Sriperumbudur, Kanchipuram, Tamil Nadu - 602105",
      isCode: "IS 13252 (Part 1):2010",
      productName: "Information Technology Equipment (Laptop / Tablet Computer)",
      brandName: "TECHNOBOOK SERIES",
      validFrom: "2023-09-01",
      validTo: "2028-08-31",
      status: "Operative",
      scheme: "Scheme-II (Compulsory Registration Scheme - CRS)"
    });
  } else if (cleanNum.length === 6 && /^[A-Z0-9]+$/i.test(cleanNum)) {
    // 6-digit HUID
    return res.json({
      valid: true,
      licenceNumber: `HUID: ${cleanNum}`,
      manufacturerName: "Kalyan Jewellers India Limited",
      factoryAddress: "AHC Centre No. 44, Zaveri Bazaar, Mumbai, Maharashtra",
      isCode: "IS 1417:2016",
      productName: "22 Karat Gold (916 Purity) Hallmark Artefact",
      brandName: "BIS 916 Hallmark with HUID",
      validFrom: "2024-06-12",
      validTo: "Lifetime Traceability",
      status: "Operative",
      scheme: "Hallmarking Scheme"
    });
  }

  // Not found / fallback test
  return res.json({
    valid: false,
    licenceNumber: cleanNum,
    status: "Invalid",
    scheme: "Unknown",
    notes: "Licence number not found in active database. Ensure you entered a valid 7-8 digit CM/L number, R-number (e.g. R-41000123), or 6-character HUID."
  });
});

// Gemini Chat Endpoint
app.post("/api/gemini/chat", async (req, res) => {
  try {
    const { prompt, mode = 'consumer', history = [] } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required" });
    }

    try {
      const openRouterResponse = await callOpenRouter(String(prompt), String(mode));
      if (openRouterResponse) {
        return res.json(openRouterResponse);
      }
    } catch (error) {
      console.warn("OpenRouter request failed; trying Gemini fallback:", error);
    }

    const ai = getGeminiClient();
    
    // Local fallback if no external AI provider is available
    if (!ai) {
      return res.json({
        text: '- Packaged drinking water is covered by **IS 14543:2016**.\n- BIS certification is mandatory under the applicable QCO.\n- The standard covers treatment, chemical limits, microbiological safety, and pesticide residues.',
        confidence: "high",
        citedClauses: [
          { clause: "Clause 4.1", description: "Treatment requirements (filtration, reverse osmosis, ozonation, and UV disinfection)." },
          { clause: "Table 2 & 3", description: "Chemical and toxic substances limits (toxic metals, bromate, and pesticide residues)." },
          { clause: "Table 4", description: "Microbiological parameters (zero E. coli, Coliform, Pseudomonas aeruginosa)." }
        ],
        sourceCard: {
          isCode: "IS 14543:2016",
          title: "Packaged Drinking Water (Other than Natural Mineral Water) — Specification",
          category: "Food & Agriculture / Mandatory QCO"
        },
        suggestedActions: [
          { label: "Download Excerpt", actionType: "download", payload: "IS 14543:2016" },
          { label: "Compare with ISO", actionType: "compare", payload: "IS 14543 vs Codex STAN 227" },
        ]
      });
    }

    const systemInstruction = `You are "BIS Sahayak", the authoritative Bureau of Indian Standards (BIS) AI Assistant and Technical Regulatory Engine for India.
Your mission is to provide accurate, clause-grounded, and mathematically precise information regarding Indian Standards (IS Codes), Quality Control Orders (QCOs), Conformity Assessment Schemes (ISI Mark Scheme-I, CRS Scheme-II, FMCS, Hallmarking HUID), and Laboratory Testing.

The user perspective is currently: ${mode.toUpperCase()} MODE (${mode === 'consumer' ? 'Focus on product safety, consumer rights, genuine ISI marks, hallmark verification, complaint filing, and health limits' : 'Focus on technical engineering limits, test methods, factory audits, QC machinery, clause compliance, and QCO timelines'}).

Output Format Rules:
1. Provide a direct, authoritative response in 3-5 short bullet points. Keep each point to one clear sentence and avoid long paragraphs.
2. Explicitly cite the Indian Standard Code (e.g., IS 10500:2012, IS 14543:2016, IS 456:2000, IS 9873, IS 1293, IS 1786, IS 13252, etc.).
3. Clearly mention specific clauses (e.g. Clause 4.1, Table 2, Clause 8.2).
4. Specify whether the standard is under mandatory Quality Control Order (QCO) or voluntary certification.
5. Keep your tone professional, crisp, simple, and scientifically sound.`;

    const contentsPrompt = `User question: "${prompt}"

Please answer with the highest technical accuracy. Return your response.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: contentsPrompt,
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.2,
      },
    });

    const rawText = formatAssistantAnswer(response.text || "No response received from model.");

    // Determine relevant IS code based on prompt keywords for citation cards
    let matchedIS = "IS 14543:2016";
    let matchedTitle = "Packaged Drinking Water (Other than Natural Mineral Water) — Specification";
    let matchedCategory = "Mandatory QCO";
    let citedClauses = [
      { clause: "Clause 4.1", description: "Mandatory multi-barrier treatment & disinfection requirements" },
      { clause: "Table 2 & 3", description: "Chemical limits and pesticide residue thresholds" }
    ];

    const lower = (prompt + " " + rawText).toLowerCase();
    if (lower.includes("10500") || lower.includes("drinking water") && !lower.includes("packaged")) {
      matchedIS = "IS 10500:2012";
      matchedTitle = "Drinking Water — Specification (Second Revision)";
      matchedCategory = "Civil & Public Health";
      citedClauses = [
        { clause: "Clause 3.1", description: "Acceptable TDS (500 mg/L) & Turbidity (1 NTU) parameters" },
        { clause: "Table 2", description: "Toxic metals tolerance: Lead (0.01 mg/L), Arsenic (0.01 mg/L)" },
        { clause: "Table 5", description: "Bacteriological requirement (0 E. coli / 100 mL)" }
      ];
    } else if (lower.includes("456") || lower.includes("concrete") || lower.includes("cement")) {
      matchedIS = "IS 456:2000";
      matchedTitle = "Plain and Reinforced Concrete — Code of Practice";
      matchedCategory = "Civil Engineering Division";
      citedClauses = [
        { clause: "Clause 6.1 (Table 2)", description: "Grades of concrete (M10 through M80)" },
        { clause: "Clause 8.2 (Table 3)", description: "Environmental exposure & minimum nominal cover requirements" },
        { clause: "Clause 35-38", description: "Limit State Design equations and safety factors" }
      ];
    } else if (lower.includes("toy") || lower.includes("9873") || lower.includes("child")) {
      matchedIS = "IS 9873 (Part 1):2019";
      matchedTitle = "Safety of Toys — Mechanical and Physical Properties";
      matchedCategory = "Consumer Goods & Child Safety";
      citedClauses = [
        { clause: "Clause 4.4", description: "Small parts cylinder testing for children under 36 months" },
        { clause: "Clause 4.7", description: "Accessible sharp edge & sharp point tolerances" },
        { clause: "Clause 5.24", description: "Drop and impact stress resistance" }
      ];
    } else if (lower.includes("plug") || lower.includes("socket") || lower.includes("1293")) {
      matchedIS = "IS 1293:2019";
      matchedTitle = "Plugs and Socket-Outlets for Domestic Purposes — Specification";
      matchedCategory = "Electrotechnical Division";
      citedClauses = [
        { clause: "Clause 8.1", description: "Protection against live pin accessibility and electric shock" },
        { clause: "Clause 13.1", description: "Maximum temperature rise limits (45K max)" },
        { clause: "Clause 20.1", description: "Resistance to heat, glow wire flammability (750°C/850°C)" }
      ];
    } else if (lower.includes("steel") || lower.includes("tmt") || lower.includes("1786") || lower.includes("rebar")) {
      matchedIS = "IS 1786:2008";
      matchedTitle = "High Strength Deformed Steel Bars and Wires for Concrete Reinforcement";
      matchedCategory = "Metallurgical Division";
      citedClauses = [
        { clause: "Clause 4.2 (Table 1)", description: "Chemical limits: Carbon (max 0.25%), Sulphur + Phosphorus" },
        { clause: "Clause 8.1 (Table 3)", description: "Mechanical properties (TS/YS ratio >= 1.10 for 500D grade)" },
        { clause: "Clause 9.3", description: "Mandatory bend & reverse rebend test compliance" }
      ];
    } else if (lower.includes("13252") || lower.includes("laptop") || lower.includes("electronics") || lower.includes("crs")) {
      matchedIS = "IS 13252 (Part 1):2010";
      matchedTitle = "Information Technology Equipment — Safety — General Requirements";
      matchedCategory = "Electronics & IT (CRS)";
      citedClauses = [
        { clause: "Clause 1.5", description: "Marking requirements with R-Number Self-Declaration" },
        { clause: "Clause 2.1", description: "SELV circuits & insulation barrier requirements" },
        { clause: "Clause 4.5", description: "Thermal and overheating limits under fault condition" }
      ];
    } else if (lower.includes("gold") || lower.includes("hallmark") || lower.includes("huid") || lower.includes("1417")) {
      matchedIS = "IS 1417:2016";
      matchedTitle = "Gold and Gold Alloys, Silver and Silver Alloys — Jewellery/Artefacts";
      matchedCategory = "Hallmarking Assaying";
      citedClauses = [
        { clause: "Clause 4.1", description: "Grades of Gold (916 for 22K, 750 for 18K, 585 for 14K)" },
        { clause: "Clause 6.2", description: "6-digit alphanumeric HUID laser marking standards" }
      ];
    }

    return res.json({
      text: rawText,
      confidence: "high",
      citedClauses: citedClauses,
      sourceCard: {
        isCode: matchedIS,
        title: matchedTitle,
        category: matchedCategory
      },
      suggestedActions: [
        { label: "Download Excerpt", actionType: "download", payload: matchedIS },
        { label: "Compare with ISO", actionType: "compare", payload: matchedIS },
      ]
    });
  } catch (error: any) {
    console.error("Gemini API error:", error);
    return res.status(500).json({
      error: "Internal server error querying standards database"
    });
  }
});

// Start Express Server with Vite integration
async function startServer() {
  if (!isProductionRuntime) {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  await initializeDatabase();

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`BIS Sahayak Server listening on port ${PORT}`);
  });
}

startServer(); 
