-- BIS Sahayak schema for Supabase PostgreSQL

CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  organisation varchar(255),
  role varchar(255),
  region varchar(255),
  access_type varchar(255) NOT NULL DEFAULT 'Enterprise portal',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.standards (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_code varchar(255) NOT NULL UNIQUE,
  title varchar(255) NOT NULL,
  category varchar(255),
  department varchar(255),
  summary text,
  scope text,
  is_mandatory_qco boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id char(36) NOT NULL,
  user_id integer REFERENCES public.users(id) ON DELETE SET NULL,
  sender varchar(20) NOT NULL CHECK (sender IN ('user', 'assistant', 'system')),
  message_text text NOT NULL,
  mode varchar(20) NOT NULL DEFAULT 'consumer' CHECK (mode IN ('consumer', 'industry')),
  confidence varchar(20),
  cited_clauses jsonb,
  source_card jsonb,
  suggested_actions jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_chat_conversation ON public.chat_messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_chat_user ON public.chat_messages (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_created ON public.chat_messages (created_at);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS users_set_updated_at ON public.users;
CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS standards_set_updated_at ON public.standards;
CREATE TRIGGER standards_set_updated_at
BEFORE UPDATE ON public.standards
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- The Express server uses the direct DATABASE_URL and is the only database client.
-- RLS is therefore intentionally not enabled for this custom-password auth schema.
-- Do not expose DATABASE_URL or password_hash to a browser client.
